name: Check npm build

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '30 5 * * *'

jobs:
  # BUILD
  build:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build production
        run: npm run build
